refactor : remove map in test
shodo-nantes/chatbots pull request #21
Opened 2023-05-25 16:12 UTC by LCaffarelli

remove all "maps" to "for...of" in tests

2023-05-25 16:14 UTC, jpiazzal requested changes

2023-05-25 16:14 UTC, jpiazzal commented on bots/birthday/birthday.test.js
> +    expect(birthdayBot.greetsBirthdays()).not.toContain('Joyeux anniversaire Gwenn Stacy');
expect should be in test :)

2023-05-26 09:02 UTC, CodeFather44 approved these changes

2023-05-26 09:14 UTC, LCaffarelli reviewed
fix : expect is now in test

2023-05-26 09:16 UTC, LCaffarelli commented on bots/birthday/birthday.test.js
> +    expect(birthdayBot.greetsBirthdays()).not.toContain('Joyeux anniversaire Gwenn Stacy');
fixed

2023-05-26 09:19 UTC, jpiazzal approved these changes
all good!

2023-05-26 09:19 UTC, merged